const size = {
  mobileS: '320px',
  mobileM: '375px',
  mobileL: '425px',
  tablet: '768px',
  laptop: '1024px',
  laptopL: '1440px',
  desktop: '2560px',
}

export const theme = {
  COLORS: {
    LIGHT_100: '#FFFFFF',
    LIGHT_200: '#FFFAF1',
    LIGHT_300: '#E1E1E6',
    LIGHT_400: '#C4C4CC',
    LIGHT_500: '#7C7C8A',
    LIGHT_600: '#76797B',
    LIGHT_700: '#4D585E',

    DARK_100: '#000405',
    DARK_200: '#00070A',
    DARK_300: '#000204',
    DARK_400: '#000A0F',
    DARK_500: '#000C12',
    DARK_600: '#00111A',
    DARK_700: '#001119',
    DARK_800: '#0D161B',
    DARK_900: '#0D1D25',
    DARK_1000: '#192227',

    GRADIENT_100: `linear-gradient(90deg, rgba(0, 10, 15, 0.272541) 0%, #000A0F 100%)`,
    GRADIENT_200: `linear-gradient(180deg, #091E26 0%, #00131C 100%)`,

    TOMATO_100: '#750310',
    TOMATO_200: '#92000E',
    TOMATO_300: '#AB222E',
    TOMATO_400: '#AB4D55',

    CARROT: '#FBA94C',
    MINT: '#04D361',

    CAKE_100: '#82F3FF',
    CAKE_200: '#065E7C',
  },
  FONTS: {
    POPPINS: {
      LIGHT_300: {
        'font-size': '2.4rem',
        'font-family': 'Poppins',
        'font-style': 'normal',
        'font-weight': '300',
        'line-height': '140%',
      },
      SEMIBOLD_600: {
        'font-size': '1.2rem',
        'font-family': 'Poppins',
        'font-style': 'normal',
        'font-weight': '600',
        'line-height': '140%',
      },
      MEDIUM_100: {
        'font-size': '1.4rem',
        'font-family': 'Poppins',
        'font-style': 'normal',
        'font-weight': '500',
        'line-height': '2.4rem',
      },
      MEDIUM_SPACED: {
        'font-size': '1.6rem',
        'font-family': 'Poppins',
        'font-style': 'normal',
        'font-weight': '400',
        'line-height': '140%',
      },
      MEDIUM_SPACED_100: {
        'font-size': '3.2rem',
        'font-family': 'Poppins',
        'font-style': 'normal',
        'font-weight': '400',
        'line-height': '140%',
      },
      MEDIUM_150: {
        'font-size': '1.8rem',
        'font-family': 'Poppins',
        'font-style': 'normal',
        'font-weight': '500',
        'line-height': '140%',
      },
      MEDIUM_200: {
        'font-size': '2rem',
        'font-family': 'Poppins',
        'font-style': 'normal',
        'font-weight': '500',
        'line-height': '160%',
      },
      MEDIUM_300: {
        'font-size': '2.4rem',
        'font-family': 'Poppins',
        'font-style': 'normal',
        'font-weight': '500',
        'line-height': '140%',
      },
      MEDIUM_350: {
        'font-size': '2.7rem',
        'font-family': 'Poppins',
        'font-style': 'normal',
        'font-weight': '500',
        'line-height': '140%',
      },
      MEDIUM_400: {
        'font-size': '3.2rem',
        'font-family': 'Poppins',
        'font-style': 'normal',
        'font-weight': '500',
        'line-height': '140%',
      },
      MEDIUM_500: {
        'font-size': '4rem',
        'font-family': 'Poppins',
        'font-style': 'normal',
        'font-weight': '500',
        'line-height': '140%',
      },
      BOLD_300: {
        'font-size': '2.4rem',
        'font-family': 'Poppins',
        'font-style': 'normal',
        'font-weight': '700',
        'line-height': '140%',
      },
      REGULAR_100: {
        'font-size': '.8rem',
        'font-family': 'Poppins',
        'font-style': 'normal',
        'font-weight': '400',
        'line-height': '140%',
      },
      REGULAR_300: {
        'font-size': '2.4rem',
        'font-family': 'Poppins',
        'font-style': 'normal',
        'font-weight': '400',
        'line-height': '140%',
      },
    },
    ROBOTO: {
      SMALLEST_REGULAR: {
        'font-size': '1.2rem',
        'font-family': 'Roboto',
        'font-style': 'normal',
        'font-weight': '400',
        'line-height': '160%',
      },
      SMALLER_REGULAR: {
        'font-size': '1.4rem',
        'font-family': 'Roboto',
        'font-style': 'normal',
        'font-weight': '400',
        'line-height': '160%',
      },
      SMALLER_BOLD: {
        'font-size': '1.4rem',
        'font-family': 'Roboto',
        'font-style': 'normal',
        'font-weight': '700',
        'line-height': '160%',
      },
      SMALL_SPACED: {
        'font-size': '1.6rem',
        'font-family': 'Roboto',
        'font-style': 'normal',
        'font-weight': '400',
        'line-height': '160%',
      },
      SMALL_REGULAR: {
        'font-size': '1.6rem',
        'font-family': 'Roboto',
        'font-style': 'normal',
        'font-weight': '400',
        'line-height': '100%',
      },
      BIG_BOLD: {
        'font-size': '2rem',
        'font-family': 'Roboto',
        'font-style': 'normal',
        'font-weight': '700',
        'line-height': '160%',
      },
      BIGGER_BOLD: {
        'font-size': '2.4rem',
        'font-family': 'Roboto',
        'font-style': 'normal',
        'font-weight': '700',
        'line-height': 'normal',
      },
      BIGGEST_BOLD: {
        'font-size': '3.2rem',
        'font-family': 'Roboto',
        'font-style': 'normal',
        'font-weight': '400',
        'line-height': '160%',
      },
      GIANT_BOLD: {
        'font-size': '4.2rem',
        'font-family': 'Roboto',
        'font-style': 'normal',
        'font-weight': '700',
        'line-height': 'normal',
      },
    },
  },
  DEVICES: {
    mobileS: `(min-width: ${size.mobileS})`,
    mobileM: `(min-width: ${size.mobileM})`,
    mobileL: `(min-width: ${size.mobileL})`,
    tablet: `(min-width: ${size.tablet})`,
    laptop: `(min-width: ${size.laptop})`,
    laptopL: `(min-width: ${size.laptopL})`,
    desktop: `(min-width: ${size.desktop})`,
    desktopL: `(min-width: ${size.desktop})`,
  },
}
